######################## Reading RTL Files #################################

puts "#             Reading RTL Files           #"

analyze -library work -format sverilog  apu_core_package.sv
analyze -library work -format sverilog  apu_defines.sv
analyze -library work -format sverilog  apu_macros.sv
analyze -library work -format sverilog  riscv_defines.sv
analyze -library work -format sverilog  riscv_alu.sv
analyze -library work -format sverilog  riscv_alu_basic.sv
analyze -library work -format sverilog  riscv_alu_div.sv
analyze -library work -format sverilog  riscv_apu_disp.sv
analyze -library work -format sverilog  riscv_compressed_decoder.sv
analyze -library work -format sverilog  riscv_config.sv
analyze -library work -format sverilog  riscv_controller.sv
analyze -library work -format sverilog  riscv_cs_registers.sv
analyze -library work -format sverilog  riscv_debug_unit.sv
analyze -library work -format sverilog  riscv_decoder.sv
analyze -library work -format sverilog  riscv_ex_stage.sv
analyze -library work -format sverilog  riscv_fetch_fifo.sv
analyze -library work -format sverilog  riscv_hwloop_controller.sv
analyze -library work -format sverilog  riscv_hwloop_regs.sv
analyze -library work -format sverilog  riscv_id_stage.sv
analyze -library work -format sverilog  riscv_if_stage.sv
analyze -library work -format sverilog  riscv_int_controller.sv
analyze -library work -format sverilog  riscv_L0_buffer.sv
analyze -library work -format sverilog  riscv_load_store_unit.sv
analyze -library work -format sverilog  riscv_mult.sv
analyze -library work -format sverilog  riscv_prefetch_buffer.sv
analyze -library work -format sverilog  riscv_prefetch_L0_buffer.sv
analyze -library work -format sverilog  riscv_register_file.sv
#analyze -library work -format sverilog  riscv_register_file_latch.sv
analyze -library work -format sverilog  riscv_tracer_defines.sv
#analyze -library work -format sverilog  riscv_tracer.sv
analyze -library work -format sverilog  riscv_core.sv
analyze -library work -format sverilog  adbg_axi_biu.sv
analyze -library work -format sverilog  adbg_axi_module.sv
analyze -library work -format sverilog  adbg_axionly_top.sv
analyze -library work -format sverilog  adbg_lint_biu.sv
analyze -library work -format sverilog  adbg_lint_module.sv
analyze -library work -format sverilog  adbg_lintonly_top.sv
analyze -library work -format sverilog  adbg_or1k_biu.sv
analyze -library work -format sverilog  adbg_or1k_module.sv
analyze -library work -format sverilog  adbg_or1k_status_reg.sv
analyze -library work -format sverilog  adbg_top.sv
analyze -library work -format sverilog  adv_dbg_if.sv
analyze -library work -format sverilog  apb_bus.sv
analyze -library work -format sverilog  apb_event_unit.sv
analyze -library work -format sverilog  apb_fll_if.sv
analyze -library work -format sverilog  apb_gpio.sv
analyze -library work -format sverilog  apb_i2c.sv
analyze -library work -format sverilog  apb_mock_uart.sv
analyze -library work -format sverilog  apb_node.sv
analyze -library work -format sverilog  apb_node_wrap.sv
analyze -library work -format sverilog  apb_pulpino.sv
analyze -library work -format sverilog  apb_regs_top.sv
analyze -library work -format sverilog  apb_spi_master.sv
analyze -library work -format sverilog  apb_timer.sv
analyze -library work -format sverilog  apb_uart.sv
#analyze -library work -format sverilog  apb_uart_sv.sv
analyze -library work -format sverilog  apb2per.sv
analyze -library work -format sverilog  AXI_2_APB.sv
analyze -library work -format sverilog  AXI_2_APB_32.sv
analyze -library work -format sverilog  axi_address_decoder_AR.sv
analyze -library work -format sverilog  axi_address_decoder_AW.sv
analyze -library work -format sverilog  axi_address_decoder_BR.sv
analyze -library work -format sverilog  axi_address_decoder_BW.sv
analyze -library work -format sverilog  axi_address_decoder_DW.sv
analyze -library work -format sverilog  axi_AR_allocator.sv
analyze -library work -format sverilog  axi_ar_buffer.sv
analyze -library work -format sverilog  axi_ArbitrationTree.sv
analyze -library work -format sverilog  axi_AW_allocator.sv
analyze -library work -format sverilog  axi_aw_buffer.sv
analyze -library work -format sverilog  axi_b_buffer.sv
analyze -library work -format sverilog  axi_BR_allocator.sv
analyze -library work -format sverilog  axi_bus.sv
analyze -library work -format sverilog  axi_buffer.sv
analyze -library work -format sverilog  axi_BW_allocator.sv
analyze -library work -format sverilog  axi_DW_allocator.sv
analyze -library work -format sverilog  axi_FanInPrimitive_Req.sv
analyze -library work -format sverilog  axi_mem_if_DP.sv
analyze -library work -format sverilog  axi_mem_if_DP_hybr.sv
analyze -library work -format sverilog  axi_mem_if_MP_Hybrid_multi_bank.sv
analyze -library work -format sverilog  axi_mem_if_multi_bank.sv
analyze -library work -format sverilog  axi_mem_if_SP.sv
analyze -library work -format sverilog  axi_mem_if_SP_wrap.sv
analyze -library work -format sverilog  axi_multiplexer.sv
analyze -library work -format sverilog  axi_node.sv
analyze -library work -format sverilog  axi_node_intf_wrap.sv
analyze -library work -format sverilog  axi_node_wrap.sv
analyze -library work -format sverilog  axi_node_wrap_with_slices.sv
analyze -library work -format sverilog  axi_r_buffer.sv
analyze -library work -format sverilog  axi_read_only_ctrl.sv
analyze -library work -format sverilog  axi_regs_top.sv
analyze -library work -format sverilog  axi_request_block.sv
analyze -library work -format sverilog  axi_response_block.sv
analyze -library work -format sverilog  axi_RR_Flag_Req.sv
analyze -library work -format sverilog  axi_slice.sv
analyze -library work -format sverilog  axi_slice_dc_master.sv
analyze -library work -format sverilog  axi_slice_dc_slave.sv
analyze -library work -format sverilog  axi_slice_wrap.sv
analyze -library work -format sverilog  axi_spi_master.sv
analyze -library work -format sverilog  axi_spi_slave.sv
analyze -library work -format sverilog  axi_spi_slave_wrap.sv
analyze -library work -format sverilog  axi_w_buffer.sv
analyze -library work -format sverilog  axi_write_only_ctrl.sv
analyze -library work -format sverilog  axi2apb.sv
analyze -library work -format sverilog  axi2apb_wrap.sv
analyze -library work -format sverilog  axi2apb32.sv
analyze -library work -format sverilog  boot_code.sv
analyze -library work -format sverilog  boot_rom_wrap.sv
analyze -library work -format sverilog  clk_rst_gen.sv
analyze -library work -format sverilog  cluster_clock_gating.sv
analyze -library work -format sverilog  cluster_clock_inverter.sv
analyze -library work -format sverilog  cluster_clock_mux2.sv
analyze -library work -format sverilog  config.sv
analyze -library work -format sverilog  core_region.sv
analyze -library work -format sverilog  core2axi.sv
analyze -library work -format sverilog  core2axi_wrap.sv
analyze -library work -format sverilog  debug_bus.sv
analyze -library work -format sverilog  defines_event_unit.sv
analyze -library work -format sverilog  dp_ram.sv
analyze -library work -format sverilog  dp_ram_wrap.sv
analyze -library work -format sverilog  generic_fifo.sv
analyze -library work -format sverilog  generic_service_unit.sv
analyze -library work -format sverilog  i2c_master_bit_ctrl.sv
analyze -library work -format sverilog  i2c_master_byte_ctrl.sv
analyze -library work -format sverilog  i2c_master_defines.sv
analyze -library work -format sverilog  instr_ram_wrap.sv
analyze -library work -format sverilog  io_generic_fifo.sv
analyze -library work -format sverilog  periph_bus_wrap.sv
analyze -library work -format sverilog  peripherals.sv
analyze -library work -format sverilog  pulp_clock_gating.sv
analyze -library work -format sverilog  pulp_clock_inverter.sv
analyze -library work -format sverilog  pulp_clock_mux2.sv
analyze -library work -format sverilog  ram_mux.sv
#analyze -library work -format sverilog  random_stalls.sv
analyze -library work -format sverilog  rstgen.sv
analyze -library work -format sverilog  sleep_unit.sv
#analyze -library work -format sverilog  sp_ram.sv
#analyze -library work -format sverilog  sp_ram_wrap.sv
analyze -library work -format sverilog  spi_master_apb_if.sv
analyze -library work -format sverilog  spi_master_axi_if.sv
analyze -library work -format sverilog  spi_master_clkgen.sv
analyze -library work -format sverilog  spi_master_controller.sv
analyze -library work -format sverilog  spi_master_fifo.sv
analyze -library work -format sverilog  spi_master_rx.sv
analyze -library work -format sverilog  spi_master_tx.sv
analyze -library work -format sverilog  spi_slave_axi_plug.sv
analyze -library work -format sverilog  spi_slave_cmd_parser.sv
analyze -library work -format sverilog  spi_slave_controller.sv
analyze -library work -format sverilog  spi_slave_dc_fifo.sv
analyze -library work -format sverilog  spi_slave_regs.sv
analyze -library work -format sverilog  spi_slave_rx.sv
analyze -library work -format sverilog  spi_slave_syncro.sv
analyze -library work -format sverilog  spi_slave_tx.sv
analyze -library work -format sverilog  timer.sv
analyze -library work -format sverilog  uart_interrupt.sv
analyze -library work -format sverilog  uart_rx.sv
analyze -library work -format sverilog  uart_tx.sv
analyze -library work -format verilog   adbg_axi_defines.v
analyze -library work -format verilog   adbg_crc32.v
analyze -library work -format verilog   adbg_defines.v
analyze -library work -format verilog   adbg_lint_defines.v
analyze -library work -format verilog   adbg_or1k_defines.v
analyze -library work -format verilog   adbg_tap_defines.v
analyze -library work -format verilog   adbg_tap_top.v
analyze -library work -format verilog   bytefifo.v
analyze -library work -format verilog   dc_data_buffer.v
analyze -library work -format verilog   dc_full_detector.v
analyze -library work -format verilog   dc_synchronizer.v
analyze -library work -format verilog   dc_token_ring.v
analyze -library work -format verilog   dc_token_ring_fifo_din.v
analyze -library work -format verilog   dc_token_ring_fifo_dout.v
analyze -library work -format verilog   defines.v
analyze -library work -format verilog   syncflop.v
analyze -library work -format verilog   syncreg.v
analyze -library work -format verilog   sp_ram_wrap.v
analyze -library work -format verilog   macro_sp_ram.v
analyze -library work -format verilog   Bank.v
analyze -library work -format vhdl      apb_uart.vhd
analyze -library work -format vhdl      uart_baudgen.vhd
analyze -library work -format vhdl      slib_clock_div.vhd
analyze -library work -format vhdl      slib_counter.vhd
analyze -library work -format vhdl      slib_edge_detect.vhd
analyze -library work -format vhdl      slib_fifo.vhd
analyze -library work -format vhdl      slib_input_filter.vhd
analyze -library work -format vhdl      slib_input_sync.vhd
analyze -library work -format vhdl      slib_mv_filter.vhd
analyze -library work -format vhdl      uart_interrupt.vhd
analyze -library work -format vhdl      uart_receiver.vhd
analyze -library work -format vhdl      uart_transmitter.vhd
analyze -library work -format sverilog  pulpino_top.sv
analyze -library work -format sverilog  pulpino_top_pads_2.sv
#analyze -library work -format verilog   tcbn65lpbwp7t.v


